version: "3.7"
services:

  # DATABASE
  postgres:
    image: postgres:14
    volumes:
      - ./postgres/scripts/flo-test-user.sql:/docker-entrypoint-initdb.d/flo-test-user.sql
    expose:
      - "5432"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

volumes:
  postgres_data:
