--TABLESPACE pg_default;
--drop table if exists public.user cascade;
create table public.user
(
    userid    bigint generated by default as identity
        constraint pk_user
            primary key,
    cognome   varchar(255) not null,
    indirizzo varchar(255) not null,
    nome      varchar(255) not null,
    password  varchar(255) not null
);
ALTER TABLE public."user" OWNER to postgres;

create database testuser  with owner postgres;
\connect testuser

--drop table if exists public.user cascade;
create table public.user
(
    userid    bigint generated by default as identity
        constraint pk_user
            primary key,
    cognome   varchar(255) not null,
    indirizzo varchar(255) not null,
    nome      varchar(255) not null,
    password  varchar(255) not null
);
ALTER TABLE public."user" OWNER to postgres;

commit;
-- alter table user add constraint user_indirizzo_key unique (indirizzo);