--TABLESPACE pg_default;
--drop table if exists public.user cascade;
create table public.user
(
    userid    bigint generated by default as identity
        constraint pk_user
            primary key,
    cognome   varchar(255) not null,
    indirizzo varchar(255) not null,
    nome      varchar(255) not null,
    password  varchar(255) not null
);
ALTER TABLE public."user" OWNER to postgres;

INSERT INTO public."user" (userid, cognome, indirizzo, nome, password) VALUES (nextval('user_userid_seq'), 'Betti', 'tp@rrr.it', 'Daniele', 'passWord');
INSERT INTO public."user" (userid, cognome, indirizzo, nome, password) VALUES (nextval('user_userid_seq'), 'Betti', 'tp@ttt.it', 'Daniele', 'passWord');
INSERT INTO public."user" (userid, cognome, indirizzo, nome, password) VALUES (nextval('user_userid_seq'), 'Betti', 'tp@lll.it', 'Daniele', 'passWord');
commit;

create database testuser  with owner postgres;
\connect testuser

--drop table if exists public.user cascade;
create table public.user
(
    userid    bigint generated by default as identity
        constraint pk_user
            primary key,
    cognome   varchar(255) not null,
    indirizzo varchar(255) not null,
    nome      varchar(255) not null,
    password  varchar(255) not null
);
ALTER TABLE public."user" OWNER to postgres;

INSERT INTO public."user" (userid, cognome, indirizzo, nome, password) VALUES (nextval('user_userid_seq'), 'Betti', 'tp@rrr.it', 'Daniele', 'passWord');
INSERT INTO public."user" (userid, cognome, indirizzo, nome, password) VALUES (nextval('user_userid_seq'), 'Betti', 'tp@ttt.it', 'Daniele', 'passWord');
INSERT INTO public."user" (userid, cognome, indirizzo, nome, password) VALUES (nextval('user_userid_seq'), 'Betti', 'tp@lll.it', 'Daniele', 'passWord');
commit;

-- alter table user add constraint user_indirizzo_key unique (indirizzo);