spring:
  application:
    name: flo-test-user
  profiles:
    active: default
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  output:
    ansi:
      enabled: never
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 5000
      idle-timeout: 300000 #5m
      max-lifetime: 600000 #10m
      register-mbeans: true
      pool-name: flotestuser
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: true

  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.flo.controller
    swagger:
      enable: false

logging:
  level:
    root: INFO
    org.hibernate: ERROR
    org.springframework.web: INFO
    com.zaxxer.hikari: INFO
    org.apache.commons: INFO
    com.flo: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
      jmx:
        exposure:
          exclude: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  security:
    enabled: true

server:
  port: 8081

user:
  username: user
  password: '$2y$10$oTY95Ypsdb0vGXxtIDWIUOC..1nsrP6Q7A1FxEruDtT62sVuQF94S' #'password' in bycrypt 11 - https://bcrypt.online/
  authorities:
    - basicAuth
